using System.IO;

namespace TeamODD.ODDB.Editors.CodeGen
{
    /// <summary>
    /// Identifies whether a .cs file in the generated output folder was produced
    /// by ODDB CodeGen. The first non-empty line of every generated file MUST
    /// start with <see cref="HeaderPrefix"/> — this is enforced by the class
    /// template at Resources/CodeGen/class.txt.
    /// </summary>
    internal static class GeneratedFileMarker
    {
        public const string HeaderPrefix = "// <auto-generated by ODDB CodeGen";

        /// <summary>True iff the file's first non-empty line begins with HeaderPrefix.</summary>
        public static bool IsGenerated(string filePath)
        {
            if (!File.Exists(filePath))
                return false;
            using var reader = new StreamReader(filePath);
            string line;
            while ((line = reader.ReadLine()) != null)
            {
                if (string.IsNullOrWhiteSpace(line))
                    continue;
                return line.StartsWith(HeaderPrefix);
            }
            return false;
        }
    }
}
